- defaults:
    link:
      create: true
      relink: true
      force: true

- link:
    ~/.config/user-dirs.dirs: misc/custom-dirs/config

- shell:
    - [xdg-user-dirs-update]
    - [for line in $(cat ~/.config/user-dirs.dirs); do export $line; done]
