- defaults:
    link:
      create: true
      relink: true
      force: true

- shell:
    - [mkdir -p ~/.fonts]
    - ["if command -v fc-cache @>/dev/null; then fc-cache -f ~/.fonts; fi", Attempting to reset fonts cache.]

- link:
    ~/.fonts: gui/fonts
