- sudo:
  - shell:
    - [(cd /tmp && curl -LO "https://github.com/dandavison/delta/releases/download/0.11.3/git-delta_0.11.3_amd64.deb"), Installing git-delta (1/3)]
    - [dpkg -i /tmp/git-delta_0.11.3_amd64.deb, Installing git-delta (2/3)]
    - [rm -f /tmp/git-delta_0.11.3_amd64.deb, Installing git-delta (3/3)]

- link:
    ~/.gitconfig: misc/git/gitconfig
    ~/.gitattributes: misc/git/gitattributes
